// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUADtz1ln6_sF5Yaqz2nG2arz4I8PHak4',
    appId: '1:933689394164:web:b599ced6e7973cb5786fa1',
    messagingSenderId: '933689394164',
    projectId: 'health-duel',
    authDomain: 'health-duel.firebaseapp.com',
    storageBucket: 'health-duel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-OaLZG4LiPnB7bhLgdYCDKP9Q8PD8gPs',
    appId: '1:933689394164:android:8a25a32678bfa910786fa1',
    messagingSenderId: '933689394164',
    projectId: 'health-duel',
    storageBucket: 'health-duel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwJRvIe-cgPP6NgnL7db8sXcep6xdUAZ4',
    appId: '1:933689394164:ios:4715479a3d4cd696786fa1',
    messagingSenderId: '933689394164',
    projectId: 'health-duel',
    storageBucket: 'health-duel.firebasestorage.app',
    iosBundleId: 'com.example.fintrackLite',
  );
}
